apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: default
type: Opaque
stringData:
  AZURE_API_KEY: "PLACEHOLDER"
  AZURE_API_BASE: "PLACEHOLDER"
  AZURE_API_VERSION: "2024-02-15-preview"
  AZURE_FOUNDRY_API_KEY: "PLACEHOLDER"
  AZURE_FOUNDRY_API_BASE: "PLACEHOLDER"
  AZURE_FOUNDRY_API_VERSION: "2024-02-15-preview"
  AZURE_GPT4_DEPLOYMENT: "gpt-4"
  AZURE_GPT5_DEPLOYMENT: "gpt-35-turbo"
