#!/bin/bash
set -e

# Configuration
RG="Sprint1-Fresh"
LOCATION="eastus"
ACR_NAME="litellmfresh$RANDOM"
OPENAI_NAME="litellm-openai-$RANDOM"
APP_PLAN="litellm-plan-fresh"
WEBAPP_NAME="litellm-fresh-$RANDOM"
IMAGE_NAME="litellm:latest"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Starting Full Azure Setup (OpenAI + App)...${NC}"

# 1. Login Check
az account show > /dev/null 2>&1 || az login

# 2. Cleanup (Optional - strictly fresh start)
if [ "$(az group exists --name $RG)" = "true" ]; then
    echo -e "${YELLOW}Resource Group $RG exists. Deleting for a fresh start...${NC}"
    az group delete --name $RG --yes --no-wait
    echo "Waiting for deletion..."
    az group wait --deleted --name $RG
fi

# 3. Create Resource Group
echo -e "${GREEN}Creating Resource Group: $RG...${NC}"
az group create -n $RG -l $LOCATION

# 4. Create Azure OpenAI Resource
echo -e "${GREEN}Creating Azure OpenAI Resource: $OPENAI_NAME...${NC}"
# Note: This requires the subscription to be allowlisted for Azure OpenAI
az cognitiveservices account create \
    --name $OPENAI_NAME \
    --resource-group $RG \
    --location $LOCATION \
    --kind OpenAI \
    --sku S0 \
    --yes

# Get Endpoint and Key
echo "Retrieving OpenAI Credentials..."
OPENAI_ENDPOINT=$(az cognitiveservices account show --name $OPENAI_NAME --resource-group $RG --query properties.endpoint -o tsv)
OPENAI_KEY=$(az cognitiveservices account keys list --name $OPENAI_NAME --resource-group $RG --query key1 -o tsv)

# 5. Deploy Models
echo -e "${GREEN}Deploying Models (gpt-4o, gpt-4o-mini)...${NC}"
# Note: Using current model versions that are not deprecated
# GPT-4 (using gpt-4o)
az cognitiveservices account deployment create \
    --name $OPENAI_NAME \
    --resource-group $RG \
    --deployment-name gpt-4 \
    --model-name gpt-4o \
    --model-version "2024-11-20" \
    --model-format OpenAI \
    --sku-capacity 10 \
    --sku-name Standard \
    || echo -e "${RED}Failed to deploy GPT-4. Check quota/region availability.${NC}"

# GPT-3.5 (using gpt-4o-mini as fallback)
az cognitiveservices account deployment create \
    --name $OPENAI_NAME \
    --resource-group $RG \
    --deployment-name gpt-35-turbo \
    --model-name gpt-4o-mini \
    --model-version "2024-07-18" \
    --model-format OpenAI \
    --sku-capacity 10 \
    --sku-name GlobalStandard \
    || echo -e "${RED}Failed to deploy GPT-3.5. Check quota/region availability.${NC}"

# 6. Update .env file
echo -e "${GREEN}Updating .env file with new credentials...${NC}"
# Backup existing .env
cp .env .env.bak 2>/dev/null || true

# We'll write a new .env or update existing. Let's append/replace.
# For simplicity/robustness, let's regenerate the relevant block.
# We are using the "Foundry" variables in app.py logic, but these are standard Azure OpenAI resources.
# However, our app logic for "azure/gpt-4" uses AZURE_FOUNDRY_API_KEY etc.
# Let's set BOTH standard and Foundry vars to point to this new resource to be safe.

cat <<EOF > .env
# Auto-generated by setup_azure_resources.sh
LITELLM_VERBOSE=True
DEFAULT_MODEL=azure/gpt-4

# Azure OpenAI Configuration (Standard)
AZURE_API_KEY=$OPENAI_KEY
AZURE_API_BASE=$OPENAI_ENDPOINT
AZURE_API_VERSION=2024-02-15-preview

# Azure Foundry Configuration (Mapped to same resource)
AZURE_FOUNDRY_API_KEY=$OPENAI_KEY
AZURE_FOUNDRY_API_BASE=$OPENAI_ENDPOINT
AZURE_FOUNDRY_API_VERSION=2024-02-15-preview
AZURE_GPT4_DEPLOYMENT=gpt-4
AZURE_GPT5_DEPLOYMENT=gpt-35-turbo 
# Note: Mapped GPT-5 var to gpt-35-turbo for testing if gpt-5 unavailable

# Other
HUGGINGFACE_API_KEY=$(grep HUGGINGFACE_API_KEY .env.bak | cut -d= -f2 || echo "")
EOF

# 7. Create ACR & Build Image
echo -e "${GREEN}Creating ACR: $ACR_NAME...${NC}"
az acr create --resource-group $RG --name $ACR_NAME --sku Standard --admin-enabled true

echo -e "${GREEN}Building and Pushing Image...${NC}"
az acr build --registry $ACR_NAME --image $IMAGE_NAME --file dockerfile .

# 8. Create App Service
echo -e "${GREEN}Creating App Service...${NC}"
az appservice plan create -g $RG -n $APP_PLAN --is-linux --sku B1
ACR_LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)
ACR_USER=$(az acr credential show -n $ACR_NAME --query username -o tsv)
ACR_PASS=$(az acr credential show -n $ACR_NAME --query passwords[0].value -o tsv)

az webapp create -g $RG -p $APP_PLAN -n $WEBAPP_NAME --container-image-name "$ACR_LOGIN_SERVER/$IMAGE_NAME"

# 9. Configure App Settings
echo -e "${GREEN}Configuring App Settings...${NC}"
az webapp config container set -g $RG -n $WEBAPP_NAME \
  --container-image-name "$ACR_LOGIN_SERVER/$IMAGE_NAME" \
  --container-registry-url "https://$ACR_LOGIN_SERVER" \
  --container-registry-user "$ACR_USER" \
  --container-registry-password "$ACR_PASS"

# Parse .env and set settings
ENV_VARS=""
while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ ! "$line" =~ ^# ]] && [[ -n "$line" ]]; then
        CLEAN_LINE=${line%%#*}
        CLEAN_LINE=$(echo "$CLEAN_LINE" | xargs)
        if [[ -n "$CLEAN_LINE" ]]; then
            ENV_VARS="$ENV_VARS $CLEAN_LINE"
        fi
    fi
done < .env

az webapp config appsettings set -g $RG -n $WEBAPP_NAME --settings $ENV_VARS

# 10. Final Output
HOSTNAME=$(az webapp show -g $RG -n $WEBAPP_NAME --query defaultHostName -o tsv)
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "App URL: https://$HOSTNAME"
echo -e "New .env file created with keys."
